apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: pip
  labels:
    product_pip-clients-entry-app: "true"
  name: pip-clients-entry-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        product_pip-clients-entry-app: "true"
    spec:
      containers:
      - image: pipregistry.azurecr.io/pip-clients/pip-clients-entry-app:1.0.0-0-rc
        name:  pip-clients-entry
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: azure-container-registry-access
---
kind: Service
apiVersion: v1
metadata:
  namespace: pip
  name: pip-clients-entry-service
  labels:
    product_pip-clients-entry-app: "true"
spec:
  selector:
    product_pip-clients-entry-app: "true"
  ports:
    - port: 80
